version: 0.2

env:
  variables: 
    DOTNET_CORE_RUNTIME: 3.1

phases:
  install: 
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
  
  pre_build:
    commands:
      - dotnet restore SeeYouRomania.Api/SeeYouRomania.Api.csproj

  build:
    commands:
      - dotnet build SeeYouRomania.Api/SeeYouRomania.Api.csproj
      - dotnet publish SeeYouRomania.Api/SeeYouRomania.Api.csproj -o ./build-output

artifacts:
  files:
    - '**/*'
  base-directory: './build-output'