version: 0.2

env:
  variables: 
    DOTNET_CORE_RUNTIME: 5.0

phases:
  install: 
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
  
  pre-build:
    commands:
      - dotnet restore SeeYouRomania.Api/SeeYouRomania.Api.csproj

  build:
    commands:
      - dotnet build SeeYouRomania.Api/SeeYouRomania.Api.csproj
      - dotnet publish SeeYouRomania.Api/SeeYouRomania.Api.csproj -o ./staging/app
  artifacts:
    files:
      - '**/*'
  base-directory: 'SeeYouRomania.Api/staging'